export const FETCH_RESTAURANT = 'FETCH_RESTAURANT'
export const FETCH_RESTAURANT_SUCCESS = 'FETCH_RESTAURANT_SUCCESS'
export const CANCEL_RESTAURANT = 'CANCEL_RESTAURANT'
export const FETCH_RESTAURANT_FAILED = 'FETCH_RESTAURANT_FAILED'