export const FETCH_RESTAURANT_DATA = 'FETCH_RESTAURANT_DATA'
export const FETCH_RESTAURANT_DATA_SUCCESS = 'FETCH_RESTAURANT_DATA_SUCCESS'
export const CANCEL_RESTAURANT_DATA = 'CANCEL_RESTAURANT_DATA'
export const FETCH_RESTAURANT_DATA_FAILED = 'FETCH_RESTAURANT_DATA_FAILED'