export const FETCH_RESTAURANT_DATA = 'FETCH_RESTAURANT'
export const FETCH_RESTAURANT_DATA_SUCCESS = 'FETCH_RESTAURANT_SUCCESS'
export const CANCEL_RESTAURANT_DATA = 'CANCEL_RESTAURANT'
export const FETCH_RESTAURANT_DATA_FAILED = 'FETCH_RESTAURANT_FAILED'