export const FETCH_RESTAURANT_DATA = 'FETCH_RESTAURANT_DATA'
export const FETCH_RESTAURANT_DATA_SUCCESS = 'FETCH_RESTAURANT_DATA_SUCCESS'
export const CANCEL_FETCH_RESTAURANT_DATA = 'CANCEL_FETCH_RESTAURANT_DATA'
export const FETCH_RESTAURANT_DATA_FAILED = 'FETCH_RESTAURANT_DATA_FAILED'

export const SEARCH_RESTAURANT_DATA = 'SEARCH_RESTAURANT_DATA'
export const SEARCH_RESTAURANT_DATA_SUCCESS = 'SEARCH_RESTAURANT_DATA_SUCCESS'
export const CANCEL_SEARCH_RESTAURANT_DATA = 'CANCEL_SEARCH_RESTAURANT_DATA'
export const SEARCH_RESTAURANT_DATA_FAILED = 'SEARCH_RESTAURANT_DATA_FAILED'